const QTDADE_MIN_LETRAS_NOME_DO_USUARIO = 3
const QTDADE_MIN_LETRAS_QUEM_PEDIU = 3
const QTDADE_MIN_LETRAS_EMAIL_DO_USUARIO = 6
const QTDADE_MIN_LETRAS_SENHA_DO_USUARIO = 6
const QTDADE_MIN_LETRAS_NOME_DA_EMPRESA = 3
const QTDADE_MIN_CARACTERES_ID_DA_PROPOSTA = 3
const QTDADE_MIN_LETRAS_ALERTA = 10

const QTDADE_MAX_LETRAS_NOME_DO_USUARIO = 30
const QTDADE_MAX_LETRAS_QUEM_PEDIU = 50
const QTDADE_MAX_LETRAS_EMAIL_DO_USUARIO = 30
const QTDADE_MAX_LETRAS_SENHA_DO_USUARIO = 12
const QTDADE_MAX_LETRAS_NOME_DA_EMPRESA = 30
const QTDADE_MAX_CARACTERES_ID_DA_PROPOSTA = 10
const DIAS_MAX_VALIDADE_DA_PROPOSTA = 1000
const QTDADE_MAX_DIGITOS_NO_VALOR_DA_PROPOSTA = 13
const QTDADE_MAX_CARACTERES_COMENTARIOS_DA_PROPOSTA = 500
const QTDADE_MAX_LETRAS_ALERTA = 50
const QTDADE_MAX_DIAS_PARA_ALERTA = 60
const TAMANHO_MAX_ARQUIVO_DA_PROPOSTA = 10 // em MB

// Alertas
const ALERTA_FOLLOWUP_CLIENTE = 'Entre em contato com o cliente'

export {
    QTDADE_MIN_LETRAS_NOME_DO_USUARIO,
    QTDADE_MIN_LETRAS_QUEM_PEDIU,
    QTDADE_MIN_LETRAS_EMAIL_DO_USUARIO,
    QTDADE_MIN_LETRAS_SENHA_DO_USUARIO,
    QTDADE_MIN_LETRAS_NOME_DA_EMPRESA,
    QTDADE_MIN_CARACTERES_ID_DA_PROPOSTA,
    QTDADE_MIN_LETRAS_ALERTA,
    QTDADE_MAX_LETRAS_NOME_DO_USUARIO,
    QTDADE_MAX_LETRAS_QUEM_PEDIU,
    QTDADE_MAX_LETRAS_EMAIL_DO_USUARIO,
    QTDADE_MAX_LETRAS_SENHA_DO_USUARIO,
    QTDADE_MAX_LETRAS_NOME_DA_EMPRESA,
    QTDADE_MAX_CARACTERES_ID_DA_PROPOSTA,
    QTDADE_MAX_DIGITOS_NO_VALOR_DA_PROPOSTA,
    DIAS_MAX_VALIDADE_DA_PROPOSTA,
    QTDADE_MAX_CARACTERES_COMENTARIOS_DA_PROPOSTA,
    QTDADE_MAX_LETRAS_ALERTA,
    QTDADE_MAX_DIAS_PARA_ALERTA,
    TAMANHO_MAX_ARQUIVO_DA_PROPOSTA,
    ALERTA_FOLLOWUP_CLIENTE
}